modLoader="javafml"
loaderVersion="*"
license="MIT"
issueTrackerURL="https://github.com/Sinytra/ConnectorExtras/issues"

[[mods]]
modId="connectorextras_terrablender_bridge"
version="${file.jarVersion}"
displayName="Connector Extras Terrablender Bridge"
authors="Su5eD"
displayURL="https://github.com/Sinytra/ConnectorExtras"
description='''
Loads TerraBlender Fabric API entrypoints of Fabric mods on Forge.
'''
displayTest = 'IGNORE_ALL_VERSION'
[[dependencies.connectorextras_terrablender_bridge]]
    modId="neoforge"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras_terrablender_bridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
