modLoader="javafml"
loaderVersion="*"
license="MIT"
issueTrackerURL="https://github.com/Sinytra/ConnectorExtras/issues"

[[mods]]
modId="connectorextras_kubejs_bridge"
version="${file.jarVersion}"
displayName="Connector Extras KubeJS Bridge"
authors="Su5eD"
displayURL="https://github.com/Sinytra/ConnectorExtras"
description='''
Provides KubeJS plugin support for Fabric mods on Forge
'''
displayTest = 'IGNORE_ALL_VERSION'
[[mixins]]
config="mixins.connectorextras_kubejs_bridge.json"
[[dependencies.connectorextras_kubejs_bridge]]
    modId="neoforge"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras_kubejs_bridge]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
