modLoader="javafml"
loaderVersion="*"
license="MIT"
issueTrackerURL="https://github.com/Sinytra/ConnectorExtras/issues"

[[mods]]
modId="connectorextras_pehkui_bridge"
version="${file.jarVersion}"
displayName="Connector Extras Pehkui Bridge"
authors="Su5eD"
displayURL="https://github.com/Sinytra/ConnectorExtras"
description='''
Compatibility bridge for Pehkui's Fabric API on Forge
'''
displayTest = 'IGNORE_ALL_VERSION'
[[mixins]]
config="mixins.pehkuibridge.json"
[[dependencies.connectorextras_pehkui_bridge]]
    modId="neoforge"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras_pehkui_bridge]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
