modLoader="javafml"
loaderVersion="*"
license="MIT"
issueTrackerURL="https://github.com/Sinytra/ConnectorExtras/issues"

[[mods]]
modId="connectorextras_jei_bridge"
version="${file.jarVersion}"
displayName="Connector Extras JEI Bridge"
authors="Su5eD"
displayURL="https://github.com/Sinytra/ConnectorExtras"
description='''
Loads JEI plugins of Fabric mods on Forge.
'''
displayTest = 'IGNORE_ALL_VERSION'
[[mixins]]
config="mixins.jeibridge.json"
[[dependencies.connectorextras_jei_bridge]]
    modId="neoforge"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
[[dependencies.connectorextras_jei_bridge]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
