name: Release

on:
  workflow_dispatch: 
    inputs: 
      release_type:
        description: 'The published artifact release type'
        required: false
        default: 'STABLE'
        type: choice
        options:
          - STABLE
          - BETA
          - ALPHA

permissions:
  actions: read
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FabricMC/fabric-action-scripts@v2
        id: changelog
        with:
          context: changelog
          workflow_id: release.yml
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21'
      - uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          gradle-home-cache-excludes: |
            gradle.properties
      - name: Build with Gradle
        run: ./gradlew clean build publishMods --stacktrace
        env:
          PUBLISH_RELEASE_TYPE: ${{ inputs.release_type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
